Document: mysldeb
Title: Debian mysldeb Manual
Author: <insert document author here>
Abstract: This manual describes what mysldeb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mysldeb/mysldeb.sgml.gz

Format: postscript
Files: /usr/share/doc/mysldeb/mysldeb.ps.gz

Format: text
Files: /usr/share/doc/mysldeb/mysldeb.text.gz

Format: HTML
Index: /usr/share/doc/mysldeb/html/index.html
Files: /usr/share/doc/mysldeb/html/*.html
